services:
  db:
    image: postgres:latest
    restart: always
    container_name: tixtrack-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ../data:/var/lib/postgresql/data
